name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Deploy
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup | Install node packages
        run: pnpm install --frozen-lockfile --prod
        env:
          NODE_ENV: production

      - name: Setup | Build
        run: pnpm build:prod
        env:
          NODE_ENV: production

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.21.0"
        env:
          NODE_ENV: production
